### ISSUE TITLE
Can't build it

### ISSUE THREAD

**Issue by Darkpepito** [mariohackandglitch/homebrew_launcher_dummy#3]
Hello,
I tried to build it, but it said some references are undefined.
They all come from cito3d, I have it but same errors are always here
What can I do ?

Thanks for your time.

**Comment by PabloMK7** [comment]
This project haven't been updated in years, probably some parts became incompatible with latest libs. I'll take a look

**Comment by PabloMK7** [comment]
Can you please check if the latest commit fixes the build issues?

**Comment by Darkpepito** [comment]
Yes, the issue is fixed, thank you !
