### ISSUE TITLE
missing png.h: cannot compile 

### ISSUE THREAD

**Issue by Alexyo21** [mariohackandglitch/homebrew_launcher_dummy#4]
hi, sorry for bothering but the code lacks the png.h so it isn't possible to compile it. 
new devkitarm 
![Snapshot_2023-05-01_02-26-15](https://user-images.githubusercontent.com/96795244/235383516-9f22254e-75f4-4f7b-a67e-ac65be701518.png)

**Comment by zybrox** [comment]
You can fix this by installing 3ds-libpng (not 3ds-png) in pacman. This works for me on Windows MSYS2.

**Comment by Alexyo21** [comment]
> You can fix this by installing 3ds-libpng (not 3ds-png) in pacman. This works for me on Windows MSYS2.

Thanks a lot
